version: "2"
services:
  app:
    container_name: iot-monitor
    image: iot-monitor
    restart: always
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:3.4
    ports:
      - "27017:27017"
    command: mongod --smallfiles